import { publicJsUrl } from "const/public-js-url";

export const template = {
  viewType: "table",
  layout: { main: true, side: false, footer: false, header: false },
  spLayout: [],
  mainContent: {
    layoutType: "default",
    layout: [
      {
        code: "homepage_creator_layout",
        type: "MULTI_LINE_TEXT",
        unit: "",
        digit: false,
        label: "homepage_creator_layout",
        style: {
          display: null,
          marginTop: null,
          textAlign: null,
          marginLeft: null,
          paddingTop: "1em",
          marginRight: null,
          paddingLeft: "1em",
          marginBottom: null,
          paddingRight: "1em",
          paddingBottom: "1em",
          verticalAlign: null,
        },
        format: null,
        noLabel: false,
        spStyle: [],
        userType: "name",
        attributes: [],
        labelStyle: {
          color: null,
          fontSize: null,
          textAlign: null,
          fontWeight: "bold",
        },
        contentStyle: {
          color: null,
          fontSize: null,
          textAlign: null,
          fontWeight: null,
        },
        spLabelStyle: [],
        unitPosition: "BEFORE",
        thumbnailSize: "150px",
        spContentStyle: [],
      },
    ],
    num: 20,
    isLinked: false,
    disableDetailLinked: false,
    isPager: true,
    style: { backgroundColor: null },
  },
  sideContent: {
    type: "rich",
    style: {
      width: "30%",
      overflowX: "auto",
      backgroundColor: "#ffffff",
    },
    content: "",
  },
  header: {
    type: "title",
    style: { height: null, overflowY: "auto", backgroundColor: null },
    content: "",
  },
  footer: {
    type: "rich",
    style: { height: null, overflowY: "auto", backgroundColor: null },
    content: "",
  },
  detailView: {
    elements: [],
    style: { backgroundColor: "#ffffff" },
    titleField: null,
    social: [],
  },
  isUseMailAuthentication: false,
  viewMailUserFilters: [],
  title: "HomepageCreator",
  isTranslate: false,
  dictionary: [],
  filters: [
    {
      with: "and",
      field: "homepage_creator_identifier",
      sign: "=",
      value: "1",
    },
  ],
  orders: [],
  isUseQuery: false,
  query: "",
  searchForms: [],
  isHeaderShown: false,
  isUseLogo: false,
  logo: null,
  isUseFavicon: false,
  favicon: null,
  headerColor: "",
  contentColor: "",
  isUseStyle: false,
  styleUrls: [],
  isUseJavaScript: true,
  javaScriptUrls: [publicJsUrl],
  hideCopyright: true,
  isUsePublicTerm: false,
  publicStartedAt: null,
  publicFinishedAt: null,
  isUseIpLimit: false,
  ips: [],
  isUseCsp: false,
  resources: [],
  isSimpleAuthentication: false,
  additionalFilters: [],
  isUseRobots: false,
  isUseErrorBackUrl: false,
  errorBackUrl: "",
  version: 1,
  users: [],
};
